### ISSUE TITLE
Installation instructions needed

### ISSUE THREAD

**Issue by jlmuir** [outpaddling/auto-admin#1]
It would be nice if `README.md` included installation instructions.  I understand that they're probably simple, but it would be helpful to state them clearly.

The installation instructions might be:

1. Download a release archive.
2. Extract the archive.
3. Change the current working directory to the extracted archive directory and run `./install`.  The `install` program behavior can be modified by setting the following environment variables: `PREFIX` (the installation prefix, but not really; if the file exists or has a size greater than zero, it will be set to a value of `/usr/local/auto-admin` on FreeBSD and `/usr/local` on Linux) and `STAGEDIR` (like `DESTDIR`).

Or, it could be that you want to say that the scripts can be installed à la carte without installing the entire Auto-admin package.

**Comment by arrowd** [comment]
The installation instruction is just `pkg install auto-admin`, just like every other FreeBSD software.

**Comment by arrowd** [comment]
Ah, sorry, I was under impression that this software is FreeBSD-specific.

**Comment by outpaddling** [comment]
Thanks for the report and sorry for the long delay.  I somehow got dropped from the watch list of my own repo and was not receiving notifications.
I added some basic install instructions, though the README still could use a lot of improvement.
