### ISSUE TITLE
install program has unusual handling of PREFIX env var

### ISSUE THREAD

**Issue by jlmuir** [outpaddling/auto-admin#2]
The install program sets the `PREFIX` environment variable to `/usr/local/auto-admin` or `/usr/local` on FreeBSD and Linux, respectively, if the file specified in the `PREFIX` environment variable exists and has a size greater than zero.  That is unusual.  Normally, the idea would be to allow the user to override the install prefix by setting the `PREFIX` environment variable.

**Comment by outpaddling** [comment]
Thanks for the report and sorry for the delay.  I somehow got dropped from the watch list of my own repo and wasn't getting notifications.
The install script was replaced some time ago by a Makefile that respects PREFIX, so I think this should be resolved.
Appreciate the feedback on this and any other issues you encounter.
