### ISSUE TITLE
auto-admin ignores ports config

### ISSUE THREAD

**Issue by tbalbers** [outpaddling/auto-admin#5]
This is just crazy, if I try to install zabbix5-server on FreeBSD 13 using auto-admin, I get a zabbix-server that will only use MySQL.
And if I go into /usr/ports/net-mgmt/zabbix5-server and do a make config and set it to use PostgreSQL, a make showconfig says:
===> The following configuration options are available for zabbix5-server-5.0.14:
     CURL=on: Support for web monitoring
     FPING=on: Build/install fping for ping checks
     IPMI=on: Support for IPMI checks
     IPV6=on: IPv6 protocol support
     LDAP=on: Support for LDAP server checks
     LIBXML2=on: Support for libxml2 (required by monitoring VMware)
     NMAP=on: Build/install nmap for o/s detection
     SSH=on: Support for SSH-based checks
     UNIXODBC=on: Support for database checks via ODBC
====> Options available for the single DB: you have to select exactly one of them
     MYSQL=off: MySQL database support
     PGSQL=on: PostgreSQL database support
     SQLITE=off: SQLite database support
     ORACLE=off: Oracle database support
====> SSL protocol support: you have to select exactly one of them
     OPENSSL=on: SSL/TLS support via OpenSSL
     GNUTLS=off: SSL/TLS support via GnuTLS
===> Use 'make config' to modify these settings

And if I then go to auto-admin and choose to install from ports, it ignores the config I just set! That pretty much makes auto-admin unusable for me.

**Comment by outpaddling** [comment]
Thanks for the report, and sorry for the delay.  I somehow got dropped from the watch list of my own repo, so I wasn't getting notified about new issues.
Can you try again with the latest?  I believe I fixed this some time ago.

**Comment by tbalbers** [comment]
On Wed, 26 Jan 2022 14:30:23 +0000 (UTC)
Jason Bacon ***@***.***> wrote:

> Thanks for the report, and sorry for the delay.  I somehow got
> dropped from the watch list of my own repo, so I wasn't getting
> notified about new issues. Can you try again with the latest?  I
> believe I fixed this some time ago.
>

Hi Jason,

I'm not able to test anytime in the near future, I'm on a contract job
and won't be home for quite a while. But thanks for getting back to me.

/tony

**Comment by outpaddling** [comment]
No problem.  I tested on wip/vsearch with the DOCS option disabled and it seems fine.  Feel free to reopen if you run into the same issue again.
